name: Deploy Node 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SSH_USER: nuit_info
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: edgar.bzh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
    - name: NPM install
      run: npm ci --include=dev
    - name: Front build
      run: |
        cp -r assets/img public
        npx parcel build
    - name: Stop the server
      run: ssh staging 'sudo /bin/systemctl stop nuit_info_main'
    - name: Check out the source
      run: scp -r *.js src public views package.json package-lock.json staging:/srv/nuit-info/
    - name: Install deps
      run: ssh staging 'cd /srv/nuit-info/; npm i'
    - name: Start the server
      if: ${{ always() }}
      run: ssh staging 'sudo /bin/systemctl start nuit_info_main'
